version: '2.0'
services:
  db:
    image: mariadb:10.5
    container_name: seatable-syncer-mysql
    volumes:
      - "/opt/seatable-syncer/mysql-data:/var/lib/mysql"  # Requested, specifies the path to MySQL data persistent store.
    environment:
      - MYSQL_ROOT_PASSWORD=PASSWORD  # Requested, set the root's password of MySQL service.
      - MYSQL_LOG_CONSOLE=true
    networks:
      - seatable-syncer-net

  seatable-syncer:
    image: seatable/seatable-syncer:latest
    container_name: seatable-syncer
    ports:
      - "5066:5066"
    volumes:
      - /opt/seatable-syncer/shared:/shared  # Requested, specifies the path to Seafile data persistent store.
    environment:
      - TIME_ZONE=Asia/Shanghai # Optional, default is UTC. Should be uncomment and set to your local time zone.
      - LOG_DIR=/shared/logs
    depends_on:
      - db
    networks:
      - seatable-syncer-net

networks:
  seatable-syncer-net:
